#version: '3.9'
#
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - redis
#
#  redis:
#    image: "redis:latest"
#    ports:
#      - "6379:6379"

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
